# Generated by Django 5.0.7 on 2024-07-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_review_book_id_review_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='bookIndex',
        ),
    ]
