# Generated by Django 5.0.7 on 2024-07-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_book_review_bookindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='bookIndex',
            new_name='book',
        ),
    ]
