# Generated by Django 5.0.7 on 2024-07-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_author_remove_book_authors_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
