# Generated by Django 5.0.7 on 2024-07-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
