# Generated by Django 5.0.7 on 2024-07-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
